# Ejemplos

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

### 

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json


### 

GET http://localhost:3000/api/products HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/products/67ae4cd956aa840c772ba434 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/products/67ae4d7956aa840c772ba435 HTTP/1.1
content-type: application/json



###

DELETE http://localhost:3000/api/products/67acde4ab55f7bf4621bb7d3 HTTP/1.1
content-type: application/json

###

DELETE https://nxapi-mongo-ana.vercel.app/api/products/67acde4ab55f7bf4621bb7d3 HTTP/1.1
content-type: application/json

### 

POST https://nxapi-mongo-ana.vercel.app/api/products HTTP/1.1
content-type: application/json


### 

DELETE https://nxapi-mongo-ana.vercel.app/api/products/67acde4ab55f7bf4621bb7d3 HTTP/1.1
content-type: application/json
